CREATE USER EF_TEST IDENTIFIED BY Password123456;
GRANT CONNECT TO EF_TEST;
GRANT ALL PRIVILEGES TO EF_TEST;
CREATE SYNONYM EF_TEST.DBMS_LOB FOR SYS.DBMS_LOB;
GRANT ALL ON SYS.DBMS_LOB TO EF_TEST;
GRANT EXECUTE ON SYS.DBMS_SQL TO EF_TEST;



CREATE USER TED_DASHBOARD IDENTIFIED BY Password123456;
GRANT CONNECT TO TED_DASHBOARD;
GRANT ALL PRIVILEGES TO TED_DASHBOARD;
CREATE SYNONYM TED_DASHBOARD.DBMS_LOB FOR SYS.DBMS_LOB;
GRANT ALL ON SYS.DBMS_LOB TO TED_DASHBOARD;
GRANT EXECUTE ON SYS.DBMS_SQL TO TED_DASHBOARD;