GRANT SELECT ON DFLOW01.dflow_docmeta_change TO DFLOW01_ESB;
GRANT SELECT ON DFLOW01.dflow_docmeta_route TO DFLOW01_ESB;
GRANT SELECT ON DFLOW01.dflow_docmeta_received TO DFLOW01_ESB;
GRANT SELECT ON DFLOW01.dflow_docbin_route TO DFLOW01_ESB;
GRANT SELECT ON DFLOW01.dflow_dm_ch_bin TO DFLOW01_ESB;
GRANT SELECT ON DFLOW01.rec_change_tracking TO DFLOW01_ESB;
GRANT SELECT ON DFLOW01.dflow_docscan_route TO DFLOW01_ESB;
GRANT SELECT ON DFLOW01.dflow_dm_ch_scan TO DFLOW01_ESB;